---
- name: Remove existing docker packages (optional)
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc

- name: Update package lists
  apt:
    update_cache: yes

- name: Install ca-certificates and curl
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
    keyurl: https://download.docker.com/linux/ubuntu/gpg

- name: Update package lists again
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
