---

- name: Add user to docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  usermod:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: docker_group_added

- name: Restart Docker service (optional)
  service:
    name: docker
    state: restarted
  when: docker_group_added.changed
