---
# tasks file for kubeadm

- name: Add Kubernetes GPG key
  become: yes
  tasks:
    - name: Download and import Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        dest: /tmp/kubernetes.gpg
        mode: 0644
    - name: Add Kubernetes GPG key
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes.gpg
  when: not path.exists("/etc/apt/keyrings/kubernetes-apt-keyring.gpg")

- name: Add Kubernetes repository for v1.28
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: present
    create: yes
    line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
