---
# tasks file for kubeadm

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Enable containerd service
  systemd:
    name: containerd
    enabled: yes

- name: Check containerd service status
  systemd:
    name: containerd
    state: started

