---
# tasks file for kubeadm

- name: Set containerd default config
  become: true
  command: containerd config default
  register: containerd_config_default

- name: Write containerd default config to file
  become: true
  copy:
    content: "{{ containerd_config_default.stdout }}"
    dest: /etc/containerd/config.toml
    mode: 0644

- name: Update SystemdCgroup setting in containerd config
  become: true
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup\s*= false'
    replace: 'SystemdCgroup = true'
