---
# tasks file for kubeadm

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install containerd.io package
  apt:
    name: containerd.io
    state: present
    update_cache: yes

