---
# tasks file for kubeadm

- name: Turn off swap
  command: swapoff -a

- name: Comment out swap entry in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^(\s*\S+\s+swap\s+\S+\s+)(\S+.*)$'
    line: '#\1\2'
    backup: yes



