---
# tasks file for kubeadm

- name: Disable swap
  command: swapoff -a

- name: Comment out swap entry in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^(\s*[^#]+\sswap\s+.*)$'
    line: '#\1'
