---
# tasks file for kubeadm

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Mark Kubernetes components on hold
  apt:
    name: "{{ item }}"
    state: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl