---
# tasks file for kubeadm

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold kubelet package
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm package
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl package
  dpkg_selections:
    name: kubectl
    selection: hold
