---
# tasks file for docker

- name: Remove existing Docker packages
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc

- name: Install required dependencies
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Add Docker's official GPG key
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository to Apt sources
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_distribution == 'Ubuntu'
  environment:
    DEBIAN_FRONTEND: noninteractive

